(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.DiarioCalculos=factory();}(this,function(){
  'use strict';
  var STATUS_POINTS={'+':3,'+-':2,'-':1,'NF':0,'A':0};
  function number(value,fallback){var n=Number(value);return isFinite(n)?n:(fallback||0);}
  function round(value,places){var p=Math.pow(10,typeof places==='number'?places:1);return Math.round((number(value)+Number.EPSILON)*p)/p;}
  function considered(original,recovery,max){var o=original===''||original===null||typeof original==='undefined'?null:number(original);var r=recovery===''||recovery===null||typeof recovery==='undefined'?null:number(recovery);var result=o===null?r:r===null?o:Math.max(o,r);if(result===null)return null;return round(Math.max(0,Math.min(number(max,10),result)),2);}
  function allocation(plan,scored,ignoreId){var qualitative=number(plan&&plan.qualitativeWeight);var total=qualitative,i;for(i=0;i<(scored||[]).length;i++)if(scored[i].id!==ignoreId)total+=number(scored[i].max);return round(total,2);}
  function canAllocate(plan,scored,value,ignoreId){var used=allocation(plan,scored,ignoreId),v=number(value);return {ok:v>0&&used+v<=10.000001,used:used,total:round(used+v,2),remaining:round(10-used,2)};}
  function qualitativeResult(activities,studentId,weight){var points=0,max=0,pending=0,results=[],i,status;for(i=0;i<(activities||[]).length;i++){status=activities[i].ratings&&activities[i].ratings[studentId];results.push(status||null);max+=3;if(status)points+=STATUS_POINTS[status]||0;else pending++;}if(!max&&number(weight)>0)pending=1;var grade=max?round(points/max*number(weight),1):0;return {points:points,maxInternal:max,weight:number(weight),grade:grade,pending:pending,results:results};}
  function studentResult(studentId,activities,scored,plan){var q=qualitativeResult(activities,studentId,plan&&plan.qualitativeWeight),direct=0,pending=q.pending,recoveryCount=0,details=[],i,note,effective;for(i=0;i<(scored||[]).length;i++){note=scored[i].grades&&scored[i].grades[studentId]||{};effective=considered(note.original,note.recovery,scored[i].max);if(effective===null)pending++;else direct+=effective;if(note.recovery!==null&&note.recovery!==''&&typeof note.recovery!=='undefined')recoveryCount++;details.push({id:scored[i].id,title:scored[i].title,max:number(scored[i].max),original:note.original===undefined?null:note.original,recovery:note.recovery===undefined?null:note.recovery,considered:effective});}var total=round(q.grade+direct,1),passing=number(plan&&plan.passingGrade,5);return {qualitative:q,scored:details,direct:round(direct,1),total:Math.min(10,total),pending:pending,recoveryCount:recoveryCount,status:pending?'pending':total>=passing?'approved':'below'};}
  function classSummary(students,activities,scored,plan){var rows=[],approved=0,below=0,pending=0,recoveries=0,sum=0,min=null,max=null,i,r;for(i=0;i<(students||[]).length;i++){r=studentResult(students[i].id,activities,scored,plan);r.id=students[i].id;r.name=students[i].name||students[i].nome;rows.push(r);recoveries+=r.recoveryCount;if(r.status==='pending')pending++;else{sum+=r.total;min=min===null?r.total:Math.min(min,r.total);max=max===null?r.total:Math.max(max,r.total);if(r.status==='approved')approved++;else below++;}}var closed=approved+below;return {rows:rows,approved:approved,below:below,pending:pending,recoveries:recoveries,average:closed?round(sum/closed,1):null,min:min,max:max};}
  return {STATUS_POINTS:STATUS_POINTS,round:round,considered:considered,allocation:allocation,canAllocate:canAllocate,qualitativeResult:qualitativeResult,studentResult:studentResult,classSummary:classSummary};
}));
