(function(root){
  'use strict';
  var KEY='cmmsf_diario_v3';
  var LEGACY_KEY='cmmsf_chamada_atividades_v1';
  function clone(o){return JSON.parse(JSON.stringify(o));}
  function iso(){return new Date().toISOString();}
  function slug(s){return String(s||'item').toLowerCase().normalize?String(s||'item').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''):String(s||'item').toLowerCase().replace(/[^a-z0-9]+/g,'-');}
  function defaultUnits(){return [{id:'u1',name:'1ª Unidade',order:1,closed:false},{id:'u2',name:'2ª Unidade',order:2,closed:false},{id:'u3',name:'3ª Unidade',order:3,closed:false}];}
  function fresh(){var cfg=clone(root.CMMSF_CONFIG_INICIAL||{}),classes=cfg.turmas||[];classes.forEach(function(c){c.name=c.nome||c.name;c.shift=c.turno||c.shift||'';c.teacher=c.professor||c.teacher||'';c.students=(c.alunos||c.students||[]).map(function(a){return {id:String(a.id),name:a.nome||a.name};});c.subjects=(c.disciplinas||[]).map(function(d){return {id:d.id||slug(d.nome||d.name),name:d.nome||d.name,active:d.ativa!==false};});delete c.alunos;delete c.disciplinas;});return {schema:'br.edu.cmmsf.diario',version:3,school:cfg.escola||{nome:'CMMSF',anoLetivo:String(new Date().getFullYear())},settings:{passingGrade:5,maxUnit:10,decimalPlaces:1},units:defaultUnits(),classes:classes,context:{classId:cfg.turmaAtualId||classes[0]&&classes[0].id||'',subjectId:'',unitId:'u1'},plans:[],records:{attendance:[],qualitative:[],scored:[],deleted:[]},official:{},updatedAt:null};}
  function normalize(db){db=db&&typeof db==='object'?db:fresh();db.schema='br.edu.cmmsf.diario';db.version=3;db.units=Array.isArray(db.units)&&db.units.length?db.units:defaultUnits();db.classes=Array.isArray(db.classes)?db.classes:[];db.context=db.context||{};db.plans=Array.isArray(db.plans)?db.plans:[];db.official=db.official&&typeof db.official==='object'?db.official:{};db.records=db.records||{};['attendance','qualitative','scored','deleted'].forEach(function(k){if(!Array.isArray(db.records[k]))db.records[k]=[];});db.settings=db.settings||{passingGrade:5,maxUnit:10,decimalPlaces:1};db.classes.forEach(function(c){c.name=c.name||c.nome||c.id;c.students=c.students||c.alunos||[];c.students=c.students.map(function(a){return {id:String(a.id),name:a.name||a.nome};});c.subjects=Array.isArray(c.subjects)?c.subjects:[];});return db;}
  function migrateLegacy(old){var db=fresh(),legacySubject={id:'nao-informada',name:'Não informada',active:true};db.classes.forEach(function(c){if(!c.subjects.length)c.subjects.push(clone(legacySubject));});db.context.subjectId='nao-informada';if(old&&old.registros){(old.registros.frequencias||[]).forEach(function(r){db.records.attendance.push({id:'att|'+r.turmaId+'|nao-informada|u1|'+r.data,classId:r.turmaId,subjectId:'nao-informada',unitId:'u1',date:r.data,absent:r.ausentes||[],createdAt:r.registradoEm||iso(),migrated:true});});(old.registros.atividades||[]).forEach(function(r){var ratings={};Object.keys(r.avaliacoes||{}).forEach(function(id){ratings[id]=r.avaliacoes[id].status;});db.records.qualitative.push({id:'qual|'+r.turmaId+'|nao-informada|u1|'+r.data+'|'+slug(r.titulo),classId:r.turmaId,subjectId:'nao-informada',unitId:'u1',date:r.data,title:r.titulo,ratings:ratings,createdAt:r.registradoEm||iso(),migrated:true});});}return db;}
  function load(){var raw=null,old=null;try{raw=localStorage.getItem(KEY);}catch(e){}if(raw){try{return normalize(JSON.parse(raw));}catch(e2){}}try{old=localStorage.getItem(LEGACY_KEY);}catch(e3){}if(old){try{return normalize(migrateLegacy(JSON.parse(old)));}catch(e4){}}return fresh();}
  function save(db){db.updatedAt=iso();localStorage.setItem(KEY,JSON.stringify(db));return db;}
  function findClass(db,id){return db.classes.filter(function(c){return c.id===id;})[0]||db.classes[0]||null;}
  function findSubject(cls,id){return cls&&(cls.subjects||[]).filter(function(s){return s.id===id;})[0]||null;}
  function planId(ctx){return [ctx.classId,ctx.subjectId,ctx.unitId].join('|');}
  function getPlan(db,ctx){var id=planId(ctx),p=db.plans.filter(function(x){return x.id===id;})[0];if(!p){p={id:id,classId:ctx.classId,subjectId:ctx.subjectId,unitId:ctx.unitId,qualitativeWeight:3,passingGrade:db.settings.passingGrade||5,closed:false,updatedAt:iso()};db.plans.push(p);}return p;}
  function inContext(item,ctx){return item.classId===ctx.classId&&item.subjectId===ctx.subjectId&&item.unitId===ctx.unitId;}
  function upsert(list,item){var i;for(i=0;i<list.length;i++)if(list[i].id===item.id){list[i]=item;return item;}list.push(item);return item;}
  function mergeImport(db,input){var items=input.turmas||input.classes||(input.id&&input.alunos?[input]:[]),summary={classes:0,students:0,subjects:0};if(!Array.isArray(items)||!items.length)throw new Error('JSON sem turmas reconhecidas.');items.forEach(function(src){var id=String(src.id||slug(src.nome||src.name)),cls=db.classes.filter(function(c){return c.id===id;})[0],newClass=!cls;if(newClass){cls={id:id,name:src.nome||src.name||id,shift:src.turno||src.shift||'',teacher:src.professor||src.teacher||'',students:[],subjects:[]};db.classes.push(cls);summary.classes++;}else{cls.name=src.nome||src.name||cls.name;cls.shift=src.turno||src.shift||cls.shift;cls.teacher=src.professor||src.teacher||cls.teacher;}var students=src.alunos||src.students||[];students.forEach(function(a){var aid=String(a.id),found=cls.students.filter(function(x){return x.id===aid;})[0];if(found)found.name=a.nome||a.name||found.name;else{cls.students.push({id:aid,name:a.nome||a.name||aid});summary.students++;}});var subjects=src.disciplinas||src.subjects||[];subjects.forEach(function(s){var sid=String(s.id||slug(s.nome||s.name)),found=cls.subjects.filter(function(x){return x.id===sid;})[0],incomingActive=s.ativa!==false&&s.active!==false,incomingName=s.nome||s.name||sid,incomingUpdatedAt=String(s.updatedAt||'');if(found){if(incomingUpdatedAt>=String(found.updatedAt||'')){found.name=incomingName;found.active=incomingActive;if(incomingUpdatedAt)found.updatedAt=incomingUpdatedAt;}}else{cls.subjects.push({id:sid,name:incomingName,active:incomingActive,updatedAt:incomingUpdatedAt||undefined});summary.subjects++;}});});return summary;}
  root.DiarioDB={KEY:KEY,clone:clone,iso:iso,slug:slug,fresh:fresh,normalize:normalize,load:load,save:save,findClass:findClass,findSubject:findSubject,getPlan:getPlan,inContext:inContext,upsert:upsert,mergeImport:mergeImport};
}(this));
