(function(root,factory){
  if(typeof module==='object'&&module.exports)module.exports=factory(require('./calculos.js'));
  else root.DiarioOficial=factory(root.DiarioCalculos);
}(this,function(C){
  'use strict';
  var state={db:null,classId:'',subjectId:'',persist:null,model:null};
  var DEFAULT_TEXTS={qualitativeLabel:'Atividades de Fixação',gradesCaption:'DIÁRIO DE CLASSE — REGISTRO DE NOTAS',frequencyCaption:'DIÁRIO DE CLASSE / LISTA DE FREQUÊNCIA',studentsPerPage:15};
  function own(o,k){return Object.prototype.hasOwnProperty.call(o||{},k);}
  function n(v){var x=Number(String(v===undefined||v===null?'':v).replace(',','.'));return isFinite(x)?x:null;}
  function round(v){return Math.round((Number(v)||0)*10)/10;}
  function fmt(v){return v===null||v===undefined||v===''?'':round(v).toFixed(1).replace('.',',');}
  function esc(v){return String(v===undefined||v===null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function repeatText(text,count){var out='',i;for(i=0;i<count;i++)out+=text;return out;}
  function slug(v){return String(v||'diario').toLowerCase().replace(/[áàâã]/g,'a').replace(/[éê]/g,'e').replace(/[í]/g,'i').replace(/[óôõ]/g,'o').replace(/[ú]/g,'u').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
  function chunks(list,size){var out=[],i;size=Math.max(1,Math.floor(Number(size)||15));for(i=0;i<list.length;i+=size)out.push(list.slice(i,i+size));return out.length?out:[[]];}
  function displayShortDate(iso){var p=String(iso||'').split('-');return p.length===3?p[2]+'/'+p[1]:iso||'';}
  function findClass(db,id){var list=db.classes||[],i;for(i=0;i<list.length;i++)if(list[i].id===id)return list[i];return null;}
  function findSubject(cls,id){var list=cls&&cls.subjects||[],i;for(i=0;i<list.length;i++)if(list[i].id===id)return list[i];return null;}
  function inContext(x,classId,subjectId,unitId){return x.classId===classId&&x.subjectId===subjectId&&x.unitId===unitId;}
  function unitList(db){var units=db&&Array.isArray(db.units)&&db.units.length?db.units:[{id:'u1',name:'1ª Unidade'},{id:'u2',name:'2ª Unidade'},{id:'u3',name:'3ª Unidade'}];return units.map(function(u,i){return {id:u.id||'u'+(i+1),name:u.name||((i+1)+'ª Unidade')};});}
  function texts(db){var src=db&&db.settings&&db.settings.official||{},out={},k;for(k in DEFAULT_TEXTS)if(own(DEFAULT_TEXTS,k))out[k]=src[k]===undefined||src[k]===null||src[k]===''?DEFAULT_TEXTS[k]:src[k];out.studentsPerPage=Math.max(1,Math.min(40,Math.floor(Number(out.studentsPerPage)||15)));return out;}
  function planFor(db,classId,subjectId,unitId){var list=db.plans||[],i,s=db.settings||{};for(i=0;i<list.length;i++)if(inContext(list[i],classId,subjectId,unitId))return list[i];return {qualitativeWeight:n(s.qualitativeWeight)===null?3:n(s.qualitativeWeight),passingGrade:n(s.passingGrade)===null?5:n(s.passingGrade)};}
  function componentList(db,classId,subjectId,unitId,qualLabel){
    var plan=planFor(db,classId,subjectId,unitId),qual=(db.records.qualitative||[]).filter(function(x){return inContext(x,classId,subjectId,unitId);}).sort(function(a,b){return String(a.date).localeCompare(String(b.date));}),scores=(db.records.scored||[]).filter(function(x){return inContext(x,classId,subjectId,unitId);}).sort(function(a,b){return String(a.date).localeCompare(String(b.date));}),out=[],period='';
    if(qual.length)period='De '+displayShortDate(qual[0].date)+' a '+displayShortDate(qual[qual.length-1].date);
    out.push({id:'qualitative',kind:'qualitative',label:qualLabel||DEFAULT_TEXTS.qualitativeLabel,max:Number(plan.qualitativeWeight)||0,date:period,records:qual});
    scores.forEach(function(x){out.push({id:x.id,kind:'scored',label:x.title||x.type||'Avaliação',max:Number(x.max)||0,date:displayShortDate(x.date||''),record:x});});
    return out;
  }
  function autoSlots(components){
    var slots=[],i,rest;
    if(components.length<=3){for(i=0;i<components.length;i++)slots.push({componentIds:[components[i].id],label:components[i].label,max:components[i].max,date:components[i].date});}
    else{
      for(i=0;i<2;i++)slots.push({componentIds:[components[i].id],label:components[i].label,max:components[i].max,date:components[i].date});
      rest=components.slice(2);slots.push({componentIds:rest.map(function(x){return x.id;}),label:'Demais avaliações',max:round(rest.reduce(function(sum,x){return sum+x.max;},0)),date:rest[rest.length-1].date});
    }
    while(slots.length<3)slots.push({componentIds:[],label:'',max:0,date:''});
    return slots;
  }
  function validateWeights(units){
    var errors=[];Object.keys(units||{}).forEach(function(uid,index){var slots=units[uid]&&units[uid].slots||[],sum=round(slots.reduce(function(t,s){return t+(Number(s.max)||0);},0));if(Math.abs(sum-10)>0.001)errors.push((index+1)+'ª unidade: os pesos somam '+fmt(sum)+'; devem somar 10,0.');});return errors;
  }
  function signature(components){return components.map(function(x){return [x.id,x.max,x.label,x.date].join(':');}).join('|');}
  function configFor(db,classId,subjectId,componentsByUnit,unitIds,qualLabel){
    var key=classId+'|'+subjectId,cfg;
    db.official=db.official||{};cfg=db.official[key]||(db.official[key]={units:{},overrides:{},finalRecovery:{},headers:{},frequency:{dates:{},values:{}}});
    cfg.units=cfg.units||{};cfg.overrides=cfg.overrides||{};cfg.finalRecovery=cfg.finalRecovery||{};cfg.headers=cfg.headers||{};cfg.frequency=cfg.frequency||{dates:{},values:{}};cfg.frequency.dates=cfg.frequency.dates||{};cfg.frequency.values=cfg.frequency.values||{};
    unitIds.forEach(function(uid){var sig=signature(componentsByUnit[uid]);if(!cfg.units[uid]||cfg.units[uid].signature!==sig){cfg.units[uid]={signature:sig,slots:autoSlots(componentsByUnit[uid])};}if(cfg.units[uid].slots[0]){cfg.units[uid].slots[0].label=qualLabel;cfg.units[uid].slots[0].date=componentsByUnit[uid][0]&&componentsByUnit[uid][0].date||'';}});
    return {key:key,cfg:cfg};
  }
  function componentValue(component,studentId,effective){
    var q,note;
    if(component.kind==='qualitative'){
      q=C.qualitativeResult(component.records,studentId,component.max);
      return component.records.length&&q.pending===0?q.grade:null;
    }
    note=component.record.grades&&component.record.grades[studentId]||{};
    if(effective)return C.considered(note.original,note.recovery,component.max);
    return note.original===undefined||note.original===null||note.original===''?null:Number(note.original);
  }
  function slotValue(slot,map,studentId,effective){var values=[],i,v;for(i=0;i<slot.componentIds.length;i++){v=map[slot.componentIds[i]]?componentValue(map[slot.componentIds[i]],studentId,effective):null;if(v===null)return null;values.push(v);}return values.length?round(values.reduce(function(a,b){return a+b;},0)):null;}
  function buildModel(db,classId,subjectId){
    var cls=findClass(db,classId),subject=findSubject(cls,subjectId),units=unitList(db),unitIds=units.map(function(u){return u.id;}),unitNames={},txt=texts(db),components={},maps={},packed,cfg,students,attendance,dateMap={},dates=[];
    if(!cls||!subject)return null;
    units.forEach(function(u){unitNames[u.id]=u.name;components[u.id]=componentList(db,classId,subjectId,u.id,txt.qualitativeLabel);maps[u.id]={};components[u.id].forEach(function(x){maps[u.id][x.id]=x;});});
    packed=configFor(db,classId,subjectId,components,unitIds,txt.qualitativeLabel);cfg=packed.cfg;
    students=(cls.students||[]).map(function(s){var perUnit={};unitIds.forEach(function(uid){var slots=cfg.units[uid].slots,originals=slots.map(function(slot,index){var k=uid+'|'+s.id+'|s'+index;return own(cfg.overrides,k)?cfg.overrides[k]:slotValue(slot,maps[uid],s.id,false);}),effective=slots.map(function(slot){return slotValue(slot,maps[uid],s.id,true);}),origComplete=originals.every(function(v){return v!==null&&v!==''&&v!==undefined;}),effComplete=effective.every(function(v){return v!==null;}),originalTotal=origComplete?round(originals.reduce(function(a,b){return a+Number(b);},0)):null,effectiveTotal=effComplete?round(effective.reduce(function(a,b){return a+Number(b);},0)):null,mkey=uid+'|'+s.id+'|media',manual=own(cfg.overrides,mkey),media=manual?cfg.overrides[mkey]:(effectiveTotal!==null?effectiveTotal:originalTotal);perUnit[uid]={slots:originals,media:media,mediaManual:manual};});return {id:String(s.id),name:s.name||s.nome,units:perUnit,finalRecovery:own(cfg.finalRecovery,s.id)?cfg.finalRecovery[s.id]:null};});
    attendance=(db.records.attendance||[]).filter(function(x){return x.classId===classId&&x.subjectId===subjectId;}).sort(function(a,b){return String(a.date).localeCompare(String(b.date));});
    attendance.forEach(function(x){if(!dateMap[x.date]){dateMap[x.date]={date:x.date,absent:{}};dates.push(dateMap[x.date]);}(x.absent||[]).forEach(function(id){dateMap[x.date].absent[String(id)]=true;});});
    return {key:packed.key,cfg:cfg,school:db.school||{},classInfo:cls,subject:subject,components:components,students:students,attendance:dates,unitIds:unitIds,unitNames:unitNames,texts:txt};
  }
  function schoolHeader(model,pageText){
    var h=model.cfg.headers,school=own(h,'school')?h.school:(model.school.nome||model.school.name||''),year=own(h,'year')?h.year:(model.school.anoLetivo||model.school.year||''),teacher=own(h,'teacher')?h.teacher:(model.classInfo.teacher||''),shift=own(h,'shift')?h.shift:(model.classInfo.shift||''),className=own(h,'className')?h.className:model.classInfo.name,subject=own(h,'subject')?h.subject:model.subject.name;
    return '<table class="official-school-header"><colgroup><col style="width:12%"><col style="width:38%"><col style="width:13%"><col style="width:37%"></colgroup><tr><td><strong>ESCOLA:</strong></td><td colspan="3"><span class="official-edit" contenteditable="true" data-official-header="school">'+esc(school)+'</span><span class="official-page-label">'+esc(pageText||'')+'</span></td></tr><tr><td><strong>COMPONENTE:</strong></td><td><span class="official-edit" contenteditable="true" data-official-header="subject">'+esc(subject)+'</span></td><td><strong>TURMA:</strong></td><td><span class="official-edit" contenteditable="true" data-official-header="className">'+esc(className)+'</span></td></tr><tr><td><strong>PROFESSOR(A):</strong></td><td><span class="official-edit" contenteditable="true" data-official-header="teacher">'+esc(teacher)+'</span></td><td><strong>ANO / TURNO:</strong></td><td><span class="official-edit" contenteditable="true" data-official-header="year">'+esc(year)+'</span> / <span class="official-edit" contenteditable="true" data-official-header="shift">'+esc(shift)+'</span></td></tr></table>';
  }
  function headerInput(value,attrs,cls){return '<input class="official-input official-header-input '+(cls||'')+'" value="'+esc(value)+'" '+attrs+'>';}
  function gradeHead(model){
    var unitIds=model.unitIds,rows=[0,1,2].map(function(slotIndex){return '<tr>'+unitIds.map(function(uid){var s=model.cfg.units[uid].slots[slotIndex],base=' data-official-unit="'+uid+'" data-official-slot="'+slotIndex+'"';return '<th class="meta-label">'+(slotIndex+1)+'ª</th><th class="official-category" colspan="2">'+headerInput(s.label,base+' data-official-slot-field="label" data-sync="'+uid+'-s'+slotIndex+'-label"','official-category-name')+headerInput(s.date,base+' data-official-slot-field="date" data-sync="'+uid+'-s'+slotIndex+'-date"','official-date')+'</th><th class="official-points">'+headerInput(fmt(s.max),base+' data-official-slot-field="max" data-sync="'+uid+'-s'+slotIndex+'-max"','official-weight')+'</th>';}).join('')+'<th class="legend-row" colspan="3">'+(slotIndex===0?'TP = TOTAL PONTOS':slotIndex===1?'MF = MÉDIA FINAL':'R FINAL = RECUPERAÇÃO FINAL')+'</th></tr>';}).join('');
    return '<thead><tr><th class="control" rowspan="5">Nº</th><th class="control" rowspan="5">NOME DO ALUNO</th>'+unitIds.map(function(uid){return '<th class="unit-title" colspan="4" data-official-unit-title="'+esc(uid)+'">'+esc(String(model.unitNames[uid]||uid).toUpperCase())+'</th>';}).join('')+'<th class="control" colspan="3">RESULTADO FINAL</th></tr>'+rows+'<tr>'+unitIds.map(function(){return '<th class="bottom-head">1ª</th><th class="bottom-head">2ª</th><th class="bottom-head">3ª</th><th class="bottom-head media-head">M</th>';}).join('')+'<th class="bottom-head">TP</th><th class="bottom-head">MF</th><th class="bottom-head">R FINAL</th></tr></thead>';
  }
  function gradeRow(student,unitIds){
    var cells=unitIds.map(function(uid){var unit=student.units[uid],slots=unit.slots.map(function(value,index){return '<td class="official-grade-cell"><input class="official-input official-grade-entry" inputmode="decimal" value="'+esc(fmt(value))+'" data-student="'+esc(student.id)+'" data-unit="'+uid+'" data-slot="'+index+'"></td>';}).join('');return slots+'<td class="official-grade-cell official-result-cell official-media-cell"><input class="official-input official-media-entry" inputmode="decimal" value="'+esc(fmt(unit.media))+'" data-student="'+esc(student.id)+'" data-unit="'+uid+'" data-manual="'+(unit.mediaManual?'1':'0')+'"></td>';}).join('');
    return '<tr data-official-student-row="'+esc(student.id)+'"><td class="official-student-number">'+esc(student.id)+'</td><td class="official-student-name"><span contenteditable="true">'+esc(student.name)+'</span></td>'+cells+'<td class="official-result-cell" data-final="tp"></td><td class="official-result-cell" data-final="mf"></td><td class="official-grade-cell"><input class="official-input official-final-recovery" inputmode="decimal" value="'+esc(fmt(student.finalRecovery))+'" data-student="'+esc(student.id)+'"></td></tr>';
  }
  function gradeColgroup(unitCount){
    var nameW,unitW,ratio=[4.4,5.6,5.6,4.7],ratioSum=20.3,cols='';
    if(unitCount===3)return '<colgroup><col style="width:2.6%"><col style="width:20%">'+repeatText('<col style="width:4.4%"><col style="width:5.6%"><col style="width:5.6%"><col style="width:4.7%">',3)+'<col style="width:5.5%"><col style="width:5.5%"><col style="width:5.5%"></colgroup>';
    nameW=unitCount<=2?24:16;unitW=(100-2.6-nameW-16.5)/unitCount;
    cols=ratio.map(function(r){return '<col style="width:'+(Math.round(unitW*r/ratioSum*100)/100)+'%">';}).join('');
    return '<colgroup><col style="width:2.6%"><col style="width:'+nameW+'%">'+repeatText(cols,unitCount)+'<col style="width:5.5%"><col style="width:5.5%"><col style="width:5.5%"></colgroup>';
  }
  function gradeSheets(model){var groups=chunks(model.students,model.texts.studentsPerPage);return groups.map(function(group,index){return '<section class="official-sheet official-grade-sheet">'+schoolHeader(model,'Notas • página '+(index+1)+' de '+groups.length)+'<p class="official-sheet-caption">'+esc(model.texts.gradesCaption)+'</p><table class="official-gradebook">'+gradeColgroup(model.unitIds.length)+gradeHead(model)+'<tbody>'+group.map(function(s){return gradeRow(s,model.unitIds);}).join('')+'</tbody></table></section>';}).join('');}
  function displayDate(iso){var p=String(iso||'').split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:iso||'';}
  function frequencySheets(model){
    var dateRecords=model.attendance.slice(),cfg=model.cfg.frequency,i,period='Datas registradas no diário',real=dateRecords.filter(function(x){return x.date;});
    if(real.length)period='De '+displayDate(real[0].date)+' a '+displayDate(real[real.length-1].date);
    if(!dateRecords.length)for(i=0;i<10;i++)dateRecords.push({date:'',absent:{}});
    var dateGroups=chunks(dateRecords,10),studentGroups=chunks(model.students,model.texts.studentsPerPage),all=[];
    dateGroups.forEach(function(dateGroup,datePage){while(dateGroup.length<10)dateGroup.push({date:'',absent:{}});studentGroups.forEach(function(group){var pageNo=all.length+1,body=group.map(function(s){var cells=dateGroup.map(function(rec,col){var global=datePage*10+col,dkey=String(global),vkey=dkey+'|'+s.id,value=own(cfg.values,vkey)?cfg.values[vkey]:(rec.date?(rec.absent[s.id]?'F':'P'):'');return '<td><input class="official-input official-frequency-value" maxlength="2" value="'+esc(value)+'" data-frequency-index="'+global+'" data-student="'+esc(s.id)+'"></td>';}).join('');return '<tr><td class="official-student-number">'+esc(s.id)+'</td><td class="official-student-name"><span contenteditable="true">'+esc(s.name)+'</span></td>'+cells+'</tr>';}).join(''),dates=dateGroup.map(function(rec,col){var global=datePage*10+col,value=own(cfg.dates,String(global))?cfg.dates[String(global)]:displayDate(rec.date);return '<th><input class="official-input official-frequency-date" maxlength="10" value="'+esc(value)+'" data-frequency-date="'+global+'"></th>';}).join('');all.push('<section class="official-sheet official-frequency-sheet">'+schoolHeader(model,'Frequência • folha '+pageNo)+'<div class="official-frequency-title">'+esc(model.texts.frequencyCaption)+'</div><table class="official-frequency-meta"><tr><td><strong>PERÍODO:</strong></td><td>'+esc(period)+'</td><td><strong>TURNO:</strong></td><td>'+esc(model.classInfo.shift||'')+'</td><td><strong>ANO:</strong></td><td>'+esc(model.school.anoLetivo||'')+'</td></tr></table><table class="official-frequency-table"><colgroup><col style="width:3.5%"><col style="width:43.5%">'+repeatText('<col style="width:5.3%">',10)+'</colgroup><thead><tr><th>Nº</th><th>NOME DO ALUNO</th>'+dates+'</tr></thead><tbody>'+body+'</tbody></table><div class="official-frequency-legend"><span><strong>P</strong> = Presença</span><span><strong>F</strong> = Falta</span><span><strong>J</strong> = Falta justificada</span><span>Professor(a): '+esc(model.classInfo.teacher||'')+'</span></div></section>');});});
    return all.join('');
  }
  function renderHtml(model,mode){if(!model)return '<div class="notice error">Selecione uma turma e uma disciplina.</div>';return (mode!=='attendance'?gradeSheets(model):'')+(mode!=='grades'?frequencySheets(model):'');}
  function inputNumber(input){return n(input.value);}
  function domUnits(scope){var out=[];scope.querySelectorAll('[data-official-unit-title]').forEach(function(th){var uid=th.getAttribute('data-official-unit-title');if(out.indexOf(uid)<0)out.push(uid);});return out;}
  function rowUnits(row){var out=[];row.querySelectorAll('.official-media-entry[data-unit]').forEach(function(x){var uid=x.getAttribute('data-unit');if(out.indexOf(uid)<0)out.push(uid);});return out;}
  function recalculate(preview){
    (preview||document).querySelectorAll('[data-official-student-row]').forEach(function(row){var medias=[],complete=true,units=rowUnits(row);units.forEach(function(uid){var entries=Array.prototype.slice.call(row.querySelectorAll('.official-grade-entry[data-unit="'+uid+'"]')),media=row.querySelector('.official-media-entry[data-unit="'+uid+'"]'),values=entries.map(function(x){return x.value===''?null:inputNumber(x);}),all=values.length===3&&values.every(function(x){return x!==null;}),sum=all?round(values.reduce(function(a,b){return a+b;},0)):null;if(media&&media.getAttribute('data-manual')!=='1'&&all){media.value=fmt(sum);}var mv=media&&media.value!==''?inputNumber(media):null;if(mv===null)complete=false;medias.push(mv);});var valid=medias.filter(function(x){return x!==null;}),tp=round(valid.reduce(function(a,b){return a+b;},0)),tpCell=row.querySelector('[data-final="tp"]'),mfCell=row.querySelector('[data-final="mf"]');tpCell.textContent=valid.length?fmt(tp):'';mfCell.textContent=complete&&units.length&&valid.length===units.length?fmt(tp/units.length):'';});
  }
  function validateDom(preview){
    var errors=[],seen={},weightByUnit={},scope=preview||document,units=domUnits(scope);
    if(!scope.querySelector('.official-grade-sheet'))return errors;
    units.forEach(function(uid){weightByUnit[uid]={};});
    scope.querySelectorAll('[data-official-slot-field="max"]').forEach(function(input){var key=input.getAttribute('data-sync');if(seen[key])return;seen[key]=true;var uid=input.getAttribute('data-official-unit'),slot=input.getAttribute('data-official-slot'),value=inputNumber(input);if(!weightByUnit[uid]){weightByUnit[uid]={};units.push(uid);}weightByUnit[uid][slot]=value===null?0:value;input.classList.toggle('invalid',value===null||value<0||value>10);});
    units.forEach(function(uid,index){var sum=round(Object.keys(weightByUnit[uid]).reduce(function(t,k){return t+(weightByUnit[uid][k]||0);},0));if(Math.abs(sum-10)>0.001)errors.push((index+1)+'ª unidade: os pesos somam '+fmt(sum)+'; o obrigatório é 10,0.');});
    scope.querySelectorAll('.official-grade-entry').forEach(function(input){var uid=input.getAttribute('data-unit'),slot=input.getAttribute('data-slot'),value=input.value===''?null:inputNumber(input),max=weightByUnit[uid]&&weightByUnit[uid][slot]||0,bad=value!==null&&(value<0||value>max);input.classList.toggle('invalid',bad);if(bad)errors.push('Há nota maior que o peso '+fmt(max)+' na '+(units.indexOf(uid)+1)+'ª unidade.');});
    scope.querySelectorAll('.official-media-entry,.official-final-recovery').forEach(function(input){var value=input.value===''?null:inputNumber(input),bad=value!==null&&(value<0||value>10);input.classList.toggle('invalid',bad);if(bad)errors.push('Há média ou recuperação final fora do intervalo de 0 a 10,0.');});
    return errors.filter(function(x,i,a){return a.indexOf(x)===i;});
  }
  function showValidation(){var box=document.getElementById('officialValidation'),preview=document.getElementById('officialPreview'),errors,button;if(!box||!preview)return [];button=document.getElementById('officialExportButton');if(!state.model){box.innerHTML='<div class="notice error"><b>Selecione ou cadastre uma disciplina para gerar o diário oficial.</b></div>';if(button)button.disabled=true;return ['Disciplina não selecionada.'];}recalculate(preview);errors=validateDom(preview);if(errors.length)box.innerHTML='<div class="notice"><b>O HTML pode ser exportado e corrigido de forma independente:</b><ul>'+errors.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ul></div>';else if(preview.querySelector('.official-grade-sheet'))box.innerHTML='<div class="notice ok"><b>Diário pronto:</b> as médias podem ser preenchidas diretamente, inclusive com notas parciais vazias.</div>';else box.innerHTML='<div class="notice ok"><b>Frequência pronta:</b> as chamadas salvas foram convertidas em P e F e podem ser editadas.</div>';if(button)button.disabled=false;return errors;}
  function debouncePersist(){clearTimeout(debouncePersist.timer);debouncePersist.timer=setTimeout(function(){if(state.persist)state.persist();},350);}
  function syncCopies(input){var key=input.getAttribute('data-sync'),value=input.value;if(!key)return;document.querySelectorAll('[data-sync="'+key+'"]' ).forEach(function(other){if(other!==input)other.value=value;});}
  function handleInput(event){
    var input=event.target,cfg=state.model&&state.model.cfg,uid,slot,field,key;if(!cfg)return;
    if(input.hasAttribute('data-sync'))syncCopies(input);
    if(input.hasAttribute('data-official-slot-field')){uid=input.getAttribute('data-official-unit');slot=Number(input.getAttribute('data-official-slot'));field=input.getAttribute('data-official-slot-field');if(cfg.units[uid]&&cfg.units[uid].slots[slot])cfg.units[uid].slots[slot][field]=field==='max'?(inputNumber(input)||0):input.value;}
    else if(input.classList.contains('official-grade-entry')){key=input.getAttribute('data-unit')+'|'+input.getAttribute('data-student')+'|s'+input.getAttribute('data-slot');cfg.overrides[key]=input.value;}
    else if(input.classList.contains('official-media-entry')){key=input.getAttribute('data-unit')+'|'+input.getAttribute('data-student')+'|media';cfg.overrides[key]=input.value;input.setAttribute('data-manual','1');}
    else if(input.classList.contains('official-final-recovery'))cfg.finalRecovery[input.getAttribute('data-student')]=input.value;
    else if(input.hasAttribute('data-frequency-date'))cfg.frequency.dates[input.getAttribute('data-frequency-date')]=input.value;
    else if(input.hasAttribute('data-frequency-index'))cfg.frequency.values[input.getAttribute('data-frequency-index')+'|'+input.getAttribute('data-student')]=input.value.toUpperCase();
    else if(input.hasAttribute('data-official-header')){field=input.getAttribute('data-official-header');cfg.headers[field]=input.textContent.trim();document.querySelectorAll('[data-official-header="'+field+'"]').forEach(function(other){if(other!==input)other.textContent=input.textContent;});}
    showValidation();debouncePersist();
  }
  function collectCss(){var css='',i,j,rules;for(i=0;i<document.styleSheets.length;i++){try{rules=document.styleSheets[i].cssRules;for(j=0;j<rules.length;j++)css+=rules[j].cssText+'\n';}catch(e){}}return css;}
  function exportGradeScriptEditable(){return [
    "(function(){",
    "function n(v){var x=Number(String(v||'').replace(',','.'));return isFinite(x)?x:null}",
    "function f(v){return (Math.round(v*10)/10).toFixed(1).replace('.',',')}",
    "function uniq(list){return list.filter(function(x,i){return list.indexOf(x)===i})}",
    "function units(scope){return uniq(Array.prototype.map.call(scope.querySelectorAll('[data-official-unit-title]'),function(x){return x.getAttribute('data-official-unit-title')}))}",
    "function rowUnits(r){return uniq(Array.prototype.map.call(r.querySelectorAll('.official-media-entry[data-unit]'),function(x){return x.getAttribute('data-unit')}))}",
    "function calc(){document.querySelectorAll('[data-official-student-row]').forEach(function(r){var medias=[],ok=true,list=rowUnits(r);list.forEach(function(u){var entries=Array.prototype.slice.call(r.querySelectorAll('.official-grade-entry[data-unit=\"'+u+'\"]')),media=r.querySelector('.official-media-entry[data-unit=\"'+u+'\"]'),values=entries.map(function(x){return x.value===''?null:n(x.value)}),all=values.length===3&&values.every(function(x){return x!==null});if(media&&media.getAttribute('data-manual')!=='1'&&all)media.value=f(values.reduce(function(a,b){return a+b},0));var mv=media&&media.value!==''?n(media.value):null;if(mv===null)ok=false;medias.push(mv)});var valid=medias.filter(function(x){return x!==null}),tp=valid.reduce(function(a,b){return a+b},0),tpCell=r.querySelector('[data-final=\"tp\"]'),mfCell=r.querySelector('[data-final=\"mf\"]');if(tpCell.getAttribute('data-manual')!=='1')tpCell.textContent=valid.length?f(tp):'';if(mfCell.getAttribute('data-manual')!=='1')mfCell.textContent=ok&&list.length&&valid.length===list.length?f(tp/list.length):''})}",
    "function validate(){var errors=[],w={},seen={},list=units(document);list.forEach(function(u){w[u]={}});document.querySelectorAll('[data-official-slot-field=\"max\"]').forEach(function(x){var k=x.getAttribute('data-sync'),u=x.getAttribute('data-official-unit');if(seen[k])return;seen[k]=1;if(!w[u]){w[u]={};list.push(u)}w[u][x.getAttribute('data-official-slot')]=n(x.value)||0});list.forEach(function(u,i){var sum=Object.keys(w[u]).reduce(function(a,k){return a+w[u][k]},0);if(Math.abs(sum-10)>.001)errors.push((i+1)+'ª unidade soma '+f(sum)+' em vez de 10,0')});document.querySelectorAll('.official-grade-entry').forEach(function(x){var v=x.value===''?null:n(x.value),m=w[x.getAttribute('data-unit')]&&w[x.getAttribute('data-unit')][x.getAttribute('data-slot')]||0,b=v!==null&&(v<0||v>m);x.classList.toggle('invalid',b);if(b)errors.push('Há nota acima do peso permitido')});document.querySelectorAll('.official-media-entry,.official-final-recovery').forEach(function(x){var v=x.value===''?null:n(x.value),b=v!==null&&(v<0||v>10);x.classList.toggle('invalid',b);if(b)errors.push('Há média ou recuperação final fora de 0 a 10')});var s=document.getElementById('exportStatus');s.textContent=errors.length?'ATENÇÃO: '+errors.filter(function(x,i,a){return a.indexOf(x)===i}).join(' • '):'Diário pronto para imprimir.';s.className=errors.length?'bad':'good';return errors}",
    "function save(){document.querySelectorAll('input').forEach(function(x){x.setAttribute('value',x.value)});var html='<!doctype html>\\n'+document.documentElement.outerHTML,blob=new Blob([html],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='diario-oficial-editado.html';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},1000)}",
    "document.addEventListener('input',function(e){var target=e.target,k=target.getAttribute&&target.getAttribute('data-sync');if(k)document.querySelectorAll('[data-sync=\"'+k+'\"]').forEach(function(x){if(x!==target)x.value=target.value});if(target.classList&&target.classList.contains('official-media-entry'))target.setAttribute('data-manual','1');if(target.getAttribute&&target.getAttribute('data-final'))target.setAttribute('data-manual','1');calc();validate()});",
    "document.getElementById('saveOfficial').onclick=save;document.getElementById('printOfficial').onclick=function(){if(validate().length&&!confirm('Há avisos matemáticos. Deseja imprimir mesmo assim?'))return;window.print()};calc();validate()}());"
  ].join('');}
  function exportScript(){var preview=document.getElementById('officialPreview');if(preview&&!preview.querySelector('.official-grade-sheet'))return "(function(){function save(){document.querySelectorAll('input').forEach(function(x){x.setAttribute('value',x.value)});var html='<!doctype html>\\n'+document.documentElement.outerHTML,blob=new Blob([html],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='diario-oficial-editado.html';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},1000)}var s=document.getElementById('exportStatus');s.textContent='Frequência pronta para imprimir.';s.className='good';document.getElementById('saveOfficial').onclick=save;document.getElementById('printOfficial').onclick=function(){window.print()}}());";return exportGradeScriptEditable();}
  function exportHtml(){
    var preview=document.getElementById('officialPreview'),clone,css,html,blob,url,a;if(!state.model){alert('Selecione ou cadastre uma disciplina.');return;}showValidation();
    clone=preview.cloneNode(true);clone.querySelectorAll('input').forEach(function(x){x.setAttribute('value',x.value);});clone.querySelectorAll('[data-final="tp"],[data-final="mf"]').forEach(function(x){x.setAttribute('contenteditable','true');x.setAttribute('title','Resultado editável somente nesta cópia');});css=collectCss();
    html='<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Diário oficial - '+esc(state.model.classInfo.name)+'</title><style>'+css+'body{margin:0;background:#d7dee4}.export-toolbar{position:sticky;top:0;z-index:20;display:flex;gap:12px;align-items:center;padding:10px 16px;background:#163a5f;color:#fff;font:14px Arial}.export-toolbar button{padding:9px 14px;border:0;border-radius:5px;background:#18794e;color:#fff;font-weight:bold}.export-toolbar .secondary{background:#1769aa}.export-toolbar .bad{color:#ffd0cc}.export-toolbar .good{color:#c8f3d9}@media print{.export-toolbar{display:none!important}}</style></head><body><div class="export-toolbar"><button id="saveOfficial" class="secondary">Baixar HTML atualizado</button><button id="printOfficial">Imprimir / salvar PDF</button><span id="exportStatus"></span></div>'+clone.innerHTML+'<script>'+exportScript()+'<\/script></body></html>';
    blob=new Blob([html],{type:'text/html;charset=utf-8'});url=URL.createObjectURL(blob);a=document.createElement('a');a.href=url;a.download='diario-oficial-'+slug(state.model.classInfo.name)+'-'+slug(state.model.subject.name)+'.html';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);
  }
  function reset(){if(!state.model)return;if(!confirm('Recriar automaticamente as três colunas de cada unidade? As edições feitas somente no modelo oficial serão apagadas.'))return;delete state.db.official[state.model.key];if(state.persist)state.persist();render({db:state.db,classId:state.classId,subjectId:state.subjectId,persist:state.persist});}
  function render(options){
    var preview=document.getElementById('officialPreview'),mode=document.getElementById('officialMode');if(!preview)return;
    state.db=options.db;state.classId=options.classId;state.subjectId=options.subjectId;state.persist=options.persist;state.model=buildModel(state.db,state.classId,state.subjectId);preview.innerHTML=renderHtml(state.model,mode?mode.value:'complete');
    if(!preview.getAttribute('data-bound')){preview.setAttribute('data-bound','1');preview.addEventListener('input',handleInput);}
    document.getElementById('officialResetButton').onclick=reset;document.getElementById('officialExportButton').onclick=exportHtml;document.getElementById('officialPrintButton').onclick=function(){var errors=showValidation();if(errors.length&&!confirm('Há avisos matemáticos. Deseja imprimir mesmo assim?'))return;window.print();};
    if(mode&&!mode.getAttribute('data-bound')){mode.setAttribute('data-bound','1');mode.onchange=function(){render({db:state.db,classId:state.classId,subjectId:state.subjectId,persist:state.persist});};}
    showValidation();
  }
  return {autoSlots:autoSlots,validateWeights:validateWeights,buildModel:buildModel,renderHtml:renderHtml,recalculate:recalculate,validateDom:validateDom,exportStandaloneScript:exportGradeScriptEditable,render:render};
}));
